/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    CustomTable: typeof import('./src/components/CustomTable.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MenuSideBarComponent: typeof import('./src/components/MenuSideBarComponent.vue')['default']
    NavigationStepper: typeof import('./src/components/NavigationStepper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
