/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/buildingPage': RouteRecordInfo<'/buildingPage', '/buildingPage', Record<never, never>, Record<never, never>>,
    '/compartimentPage': RouteRecordInfo<'/compartimentPage', '/compartimentPage', Record<never, never>, Record<never, never>>,
    '/homePage': RouteRecordInfo<'/homePage', '/homePage', Record<never, never>, Record<never, never>>,
    '/potPage': RouteRecordInfo<'/potPage', '/potPage', Record<never, never>, Record<never, never>>,
    '/requestPage': RouteRecordInfo<'/requestPage', '/requestPage', Record<never, never>, Record<never, never>>,
    '/speciesFormPage': RouteRecordInfo<'/speciesFormPage', '/speciesFormPage', Record<never, never>, Record<never, never>>,
    '/speciesPage': RouteRecordInfo<'/speciesPage', '/speciesPage', Record<never, never>, Record<never, never>>,
    '/userPage': RouteRecordInfo<'/userPage', '/userPage', Record<never, never>, Record<never, never>>,
  }
}
