/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/building/buildingFormPage': RouteRecordInfo<'/building/buildingFormPage', '/building/buildingFormPage', Record<never, never>, Record<never, never>>,
    '/building/buildingsPage': RouteRecordInfo<'/building/buildingsPage', '/building/buildingsPage', Record<never, never>, Record<never, never>>,
    '/canvas/modelingPage': RouteRecordInfo<'/canvas/modelingPage', '/canvas/modelingPage', Record<never, never>, Record<never, never>>,
    '/canvas/plantingPage': RouteRecordInfo<'/canvas/plantingPage', '/canvas/plantingPage', Record<never, never>, Record<never, never>>,
    '/compartiments/compartimentFormPage': RouteRecordInfo<'/compartiments/compartimentFormPage', '/compartiments/compartimentFormPage', Record<never, never>, Record<never, never>>,
    '/compartiments/compartimentPage': RouteRecordInfo<'/compartiments/compartimentPage', '/compartiments/compartimentPage', Record<never, never>, Record<never, never>>,
    '/connexion/loginPage': RouteRecordInfo<'/connexion/loginPage', '/connexion/loginPage', Record<never, never>, Record<never, never>>,
    '/containers/containerFormPage': RouteRecordInfo<'/containers/containerFormPage', '/containers/containerFormPage', Record<never, never>, Record<never, never>>,
    '/containers/containersPage': RouteRecordInfo<'/containers/containersPage', '/containers/containersPage', Record<never, never>, Record<never, never>>,
    '/homePage': RouteRecordInfo<'/homePage', '/homePage', Record<never, never>, Record<never, never>>,
    '/requests/requestFormPage': RouteRecordInfo<'/requests/requestFormPage', '/requests/requestFormPage', Record<never, never>, Record<never, never>>,
    '/requests/requestInformationPage': RouteRecordInfo<'/requests/requestInformationPage', '/requests/requestInformationPage', Record<never, never>, Record<never, never>>,
    '/requests/requestsPage': RouteRecordInfo<'/requests/requestsPage', '/requests/requestsPage', Record<never, never>, Record<never, never>>,
    '/species/specieFormPage': RouteRecordInfo<'/species/specieFormPage', '/species/specieFormPage', Record<never, never>, Record<never, never>>,
    '/species/speciesPage': RouteRecordInfo<'/species/speciesPage', '/species/speciesPage', Record<never, never>, Record<never, never>>,
  }
}
